website/apps/__init__.py
from flask import Flask



def create_app():
    
    app = Flask(__name__)
    from .views import view
    from .auth import auth
    
    app.register_blueprint(view,url_prefix="/")
    app.register_blueprint(auth,url_prefix="/")
    
    return app

website/apps/auth.py
from flask import Blueprint

auth = Blueprint("auth","__name'__")

website/apps/views.py
from flask import Blueprint,redirect,render_template,flash,get_flashed_messages

view = Blueprint("view",__name__)


@view.route("/",methods=["POST","GET"])
def index():
    
    return render_template("home.html")
    

website/apps/templates/_post.html
 
<h2 align="center">Posts</h2>

{% if posts %}
{% for post in posts %}
<div  class="card">
    <div class="imgbx"><img src=""></div>
    <div class="userdets">
    <a href="{{ url_for("post",username=post.author.username)}}"><h2>{{ post.author.Username}}</h2></a>
    </div>
    <div class="container">
        {% if current_user.id == post.author.id %}
        <div class="drop"><button><a href="{{url_for("delete",id=post.author.username)}}">Delete</a></div>
        
        {% endif %}
        <ul>
            <li >
                
            {{ post.body }}<br> <h2>{{ post.Time_stamp}}</h2>
            </li>
        </ul>
        <div class="comment">
            
            
            {% for comment in post.Comment %}
            
                    <li>{{ comment.body }} 
                        {% if current_user.id == comment.writter.id or current_user.id==post.author%}
                        <small><a href="{{url_for('delete_comment',comment_id=comment.id)}}"><button style="padding-left:100px;">delete</button></a></small></li><br>
                        {% endif %}
          
            {% endfor %}
           
        </div>
    </div><br>
    {% if current_user %}
        <div class="form">
        <form action= "{{ url_for('create_comment',post_id=post.id) }}" method="post">
            <input placeholder="Comment" type="Text" id="Text" name="Text"/>

            <button>Comment</button>
    {% endif %}
    </form>
        </div>
</div>

</div>
<br>
{% endfor %}
{% else %}
<h2> No Post yet!</h2>
{% endif %}

    
         
 

website/apps/templates/base.html
<!doctype html>
<html>
    <head>
         
        {% if title %}
            <title>{{ title }}</title>
        {% else %}
        <title> Menscape </title>
        {% endif %}
         
        <link rel="stylesheet" href="{{url_for('static',filename='css/main.css')}}">
    </head>
    <body>
        {% with message = get_flashed_messages() %}
        {%if message %}
        {% for msg in message %}
        <ul><li>{{ msg }}</li></ul>
        {% endfor %}
        {% endif %}
        {% endwith %}
        <nav >
          
            
            <h2> Men<span>scape</span></h2>
                <ul>
                    <a href="{{ url_for('view.index')}}"><li>Home</li></a>
                    
                     
                </ul>
             
            </nav>
       
        {% block content %}
        {% endblock %}
    </body>
     

</html>

website/apps/templates/confirm.html
{% extends 'base.html' %}
{% block content %}

<h1> A link has been sent to your email click to confirm</h1>

{% endblock %}

website/apps/templates/home.html
{% extends 'base.html'%}
{% block content %}

<p>Hello world,    This menscape blog page....</p>

{% include '_post.html' %}
   
{% endblock%}

website/apps/templates/login.html
{% extends 'base.html'%}
{% block content %}
<hr>
 
<div>
<h2>Login</h2>
<form action="" method="post" novalidate >
{{  form.hidden_tag()  }}
<p> Don't have an account? click <a href="{{ url_for('reg')}}">here</a>
<p>{{ form.Username.label()}}<br>
    
{{ form.Username(size=20,placeholder="Username",height=25)}}</p>
<br>
{% for error in form.Username.errors %}
<span style="color:red;">{{ error }}</span>
{% endfor %}


<p>{{ form.Password.label()}}<br>
{{ form.Password(size=25,placeholder="Password",height=25)}}</p>

{% for error in form.Password.errors %}
<span style="color:red">{{ error }}</span>
<br>
{% endfor %}
 
{{ form.Remember_me()}}
{{ form.Login()}}

</form>
</div>

{% endblock %}

website/apps/templates/make_post.html
{% extends 'base.html' %}
{% block content %}

<form action="" method="post">
    <p>Make a post</p>
    {{ form.hidden_tag() }}
    {{ form.Text() }}
</br>
    {{ form.Post}}

</form>


{% endblock %}

website/apps/templates/post.html
{% extends 'base.html'%}
{% block content %} 

{% include '_post.html' %}
<div class="create" align="center"><button><a href="{{url_for("create")}}">Create</a></div>
<div class="back"><button><a href="{{url_for("home")}}">Back</a></div>
{% endblock %}

website/apps/templates/profile.html
{% extends 'base.html' %}
{% block content %}

<h1 align="center"> {{ current_user}} Posts</h1>
<button><a href="{{ url_for("create") }} ">Create post</a></button>


{% if posts %}
{% for post in posts %}
<div  class="card">
<div>
    <div class="container">
<ul>
    <li>
        
    {{ post.body }}<br> {{ post.Time_stamp}}
    </li><br>
</ul>
{% endfor %}
{% else %}
<h2> No Post yet!</h2>

</div>
    


{% endif %}

    
             
     


{% endblock %}

website/apps/templates/reg.html
{% extends 'base.html'%}
{% block content %}
<hr>

<div>
<h2>Register</h2>
<form action="" method="post" novalidate >
{{  form.hidden_tag()  }}
<p>{{ form.Username.label()}}<br>
{{ form.Username(size=30,placeholder="Username",height=25)}}</p>
{% for error in form.Username.errors %}
<span style="color:red;">{{ error }}</span>
{% endfor %}
<p>{{ form.Email.label()}}<br>
{{ form.Email(size=30,placeholder="Email",height=25)}}</p>
{% for error in form.Email.errors %}
<span style="color:red;">{{ error }}</span>
{% endfor %}

<p>{{ form.Password.label()}}<br>
{{ form.Password(size=35,placeholder="Passsword",height=25)}}</p>
{% for error in form.Password.errors %}
<span style="color:red">{{ error }}</span>
{% endfor %}
<p>{{ form.Pass.label()}}<br>
{{ form.Pass(size=35,placeholder="Re-enter Password",height=25)}}</p>
{% for error in form.Pass.errors %}
<span style="color:red">{{ error }}</span>
{% endfor %}


{{ form.Submit()}}

</form>
</div>

{% endblock %}

website/apps/templates/te.html
<!DOCTYPE html>
<html>
    <head>
        <title>Wizard of oz</title>
    </head>
    <body>
        <h1>Princess is flying with her horse a unicorn horse over a high mountain==</h1>
    </body>
    <footer>
        Footer
    </footer>
    
</html>

website/apps/templates/view.html
{% extends 'base.html' %}
{% block content %}

<table>
    <tr>
        <td>{{current_user.Username}} says: This is my blog posts</td>
    <tr>
</table>
{% endblock %}